<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 arcade_machine_own.glb --transform
-->

<script>
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	let { fallback, error, children, ref = $bindable(), ...props } = $props()

	const gltf = useGltf('/models/arcade_machine_own-transformed.glb')
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Screen.geometry}
			material={gltf.materials.Screen}
			position={[0, 1.38, 0.14]}
			scale={1.01}
		/>
		<T.Mesh
			geometry={gltf.nodes.BodyMesh.geometry}
			material={gltf.materials['machine body main']}
			position={[0.28, 0, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.LeftCover.geometry}
			material={gltf.materials['machine body outer']}
			position={[0.3, 1.21, -0.13]}
		/>
		<T.Mesh
			geometry={gltf.nodes.RightCover.geometry}
			material={gltf.materials['machine body outer']}
			position={[-0.3, 1.21, -0.13]}
			scale={[-1, 1, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.ScreenFrame.geometry}
			material={gltf.materials['screen frame']}
			position={[0.28, 0.06, 0.03]}
		/>
		<T.Mesh
			geometry={gltf.nodes.joystick_base.geometry}
			material={gltf.materials['joystick base']}
			position={[0.13, 0.96, -0.2]}
			rotation={[-0.19, 0, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Main_Button_Enclosure.geometry}
			material={gltf.materials['joystick base']}
			position={[-0.11, 0.98, -0.09]}
			rotation={[-0.18, 0, 0]}
			scale={0.94}
		>
			<T.Mesh
				geometry={gltf.nodes.Main_Button.geometry}
				material={gltf.materials['joystick cap']}
				position={[0, 0.01, 0]}
				rotation={[0.19, 0, 0]}
				scale={0.72}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.joystick_stick_application.geometry}
			material={gltf.materials['joystick base']}
			position={[0.13, 0.97, -0.2]}
			rotation={[-0.19, 0, 0]}
		>
			<T.Mesh
				geometry={gltf.nodes.joystick_stick.geometry}
				material={gltf.materials['joystick stick']}
				position={[0, -0.01, 0]}
			>
				<T.Mesh
					geometry={gltf.nodes.joystick_cap.geometry}
					material={gltf.materials['joystick cap']}
					position={[0, 0.11, 0]}
				/>
			</T.Mesh>
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
